### ISSUE TITLE
Compile Issue while building.

### ISSUE THREAD

**Issue by OmerFarukOruc** [aced1a/IotControl#1]
com\iot\control\infrastructure\dao\LogDao.java:25:

error: An abstract DAO method must be annotated with one and only one of the following annotations: Insert,Delete,Query,Update,Upsert,RawQuery
public abstract java.lang.Object add(@org.jetbrains.annotations.NotNull

**Comment by OmerFarukOruc** [comment]
How it's completed as closed? At least I would like to see a comment.

**Comment by diaquz** [comment]
The add method was incorrectly annotated with @Inject instead of @Insert, causing an error.
